### ISSUE TITLE
[RFC] CDLF-0000E-00 - Message Pack input

### ISSUE THREAD

**Issue by esavier** [epiphany-platform/CommonDataLayer#258] opened 2021-02-17 02:00 UTC
Research and provide the RFC with the findings on the possibility to use MessagePack as an input format for the CDL.

**Comment by luke-biel** [comment] 2021-02-17 12:25
This is a duplicate of https://github.com/epiphany-platform/CommonDataLayer/issues/226

**Closed** 2021-03-10 12:53 UTC
